default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 5000
  username: iami
  password: <%= ENV["IAMI_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: tests_dev

test:
  <<: *default
  database: tests_test

production:
  <<: *default
  database: tests_garage
